{% set name = "test-drive" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fortran-lang/test-drive/releases/download/v{{ version }}/test-drive-{{ version }}.tar.xz
  sha256: 38c29f9366ed6fb90ff10fcb7efe2cebf2f3ba003edb08e6f56d2d758a070cee

build:
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}  # [unix]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - test ! -f $PREFIX/lib/lib{{ name }}.a  # [unix]

about:
  home: https://github.com/fortran-lang/test-drive
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-Apache
    - LICENSE-MIT
  summary: >-
    Simple testing framework for Fortran

extra:
  recipe-maintainers:
    - awvwgk
    - mwtoews
